name: Sync Feedback to GitHub Issues

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install specific dependencies
        run: npm install @octokit/rest firebase-admin
        
      - name: Create directory structure
        run: |
          mkdir -p /tmp/credentials
          mkdir -p feedback_logs/screenshots
        
      - name: Prepare Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > /tmp/credentials/service-account.json
          ls -la /tmp/credentials/service-account.json

      - name: Check GitHub Token
        run: |
          echo "Testing GitHub token..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user
      
      - name: Sync Feedback to Issues
        run: |
          # Create test file to verify write permissions
          echo "Test content" > feedback_logs/test.txt
          node scripts/sync-firestore-to-github.js
          ls -la feedback_logs/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT_PATH: /tmp/credentials/service-account.json
          GITHUB_OWNER: 'judinilson'
          GITHUB_REPO: 'APP'
          
      - name: Debug Artifacts
        if: always()
        run: |
          echo "Contents of feedback_logs directory:"
          ls -R feedback_logs/
        
      - name: List Feedback Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: feedback-logs
          path: feedback_logs/
          retention-days: 30
