name: Sync Feedback to GitHub Issues

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  sync-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install specific dependencies
        run: npm install @octokit/rest firebase-admin

      - name: Validate service account format
        run: |
          # Extract first 10 and last 10 characters to avoid printing the whole key
          FIRST_10=$(echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | cut -c1-10)
          LAST_10=$(echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | rev | cut -c1-10 | rev)
          echo "First 10 chars: $FIRST_10 ... Last 10 chars: $LAST_10"
          # Test if it's valid base64
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d | head -c 20
            
      - name: Sync Feedback to Issues
        run: node scripts/sync-firestore-to-github.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GITHUB_OWNER: 'dnre'
          GITHUB_REPO: 'APP'
          PROJECT_NAME: 'Dnre-bug-tracking'
