name: Sync Feedback to GitHub Issues

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: read
  repository-projects: write
  organization-projects: write

jobs:
  sync-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install specific dependencies
        run: npm install @octokit/rest firebase-admin
        
      - name: Prepare Firebase credentials
        run: |
          mkdir -p /tmp/credentials
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > /tmp/credentials/service-account.json
          ls -la /tmp/credentials/service-account.json
      
      - name: Debug GitHub permissions
        run: |
          echo "GitHub Token Permissions:"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
          
      - name: List available projects
        run: |
          echo "Organisation Projects:"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/${{ env.GITHUB_OWNER }}/projects" || echo "Failed to fetch org projects"
          echo "\n\nRepository Projects:"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ env.GITHUB_OWNER }}/${{ env.GITHUB_REPO }}/projects" || echo "Failed to fetch repo projects"
        env:
          GITHUB_OWNER: 'dnre'
          GITHUB_REPO: 'APP'
          
      - name: Sync Feedback to Issues
        run: node scripts/sync-firestore-to-github.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT_PATH: /tmp/credentials/service-account.json
          GITHUB_OWNER: 'dnre'
          GITHUB_REPO: 'APP'
          PROJECT_NAME: 'Dnre-bug-tracking'
