name: Sync Feedback to GitHub Issues

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  repository-projects: write
  organization-projects: write  # If using org projects

jobs:
  sync-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install specific dependencies
        run: npm install @octokit/rest @octokit/graphql firebase-admin

      - name: Prepare Firebase credentials
        run: |
          # Create a temporary directory for credentials
          mkdir -p /tmp/credentials
          
          # Decode the base64 secret to a JSON file
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > /tmp/credentials/service-account.json
          
          # Check that the file exists and has content (no sensitive data)
          ls -la /tmp/credentials/service-account.json
          
      - name: Sync Feedback to Issues
        run: node scripts/sync-firestore-to-github.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT_PATH: /tmp/credentials/service-account.json
          GITHUB_OWNER: 'dnre'
          GITHUB_REPO: 'APP'
          PROJECT_NAME: 'Dnre-bug-tracking'
