name: Sync Feedback to GitHub Issues

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  sync-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install specific dependencies
        run: npm install @octokit/rest firebase-admin
        
      - name: Sync Feedback to Issues
        run: node scripts/sync-firestore-to-github.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GITHUB_OWNER: 'dnre'
          GITHUB_REPO: 'APP'
          PROJECT_NAME: 'Dnre-bug-tracking'
